--- 
Google-chrome: 
  \Cv: \Cs
  \Ci: \[Page_Down]
  \Cw: \[Page_Up]
  \Ct: \C\[Page_Down]
  \Cp: \C\[Page_Up]
  \C/: \Cz
  \Cu: \Cv
  \At: \Ct
  \An: \Cn
  \Aw: \Cw
  \Al: \Cl
  \Ag: \C\[End]
  \Au: \C\[Home]
  \Aa: \Ca
  \Az: \Cz
  \Ax: \Cx
  \Ac: \Cc
  \Av: \Cv
  \AN: \CN
  \Cg: \[Escape]
  \Cj: \[Down]
  \Ck: \[Up]
Gnome-terminal:
  \Ct: \C\[Page_Down]
  \Cp: \C\[Page_Up]
  \Av: \CV
  \Ac: \CC
  \At: \CT
  \An: \CN
  \Aw: \CW
  \Aq: \CQ
  \Cj: \[Down]
  \Ck: \[Up]
Eclipse:
  \Cg: \[Escape]
Emacs:
  \Ci: \At
  \Cm: \Ay