set -g mouse on
# Switch to previous session with Ctrl + Up
bind-key -n S-Up switch-client -p

# Switch to next session with Ctrl + Down
bind-key -n S-Down switch-client -n

# Default text color to black for high contrast on light backgrounds
set -g status-fg black

# Assigns a unique, distinct light color based on the session's ID
set-hook -g session-created 'run-shell " \
    COLORS=(217 229 157 159 147 183 252); \
    ID=\$(tmux display-message -p \"#{session_id}\" | tr -d \"\$\"); \
    INDEX=\$((\$ID % \${#COLORS[@]})); \
    tmux set-option -t #{session_name} status-style bg=colour\${COLORS[\$INDEX]},fg=black"'

set-window-option -g aggressive-resize on
