#!/usr/bin/env bash
# -*- mode: sh; -*-

source ~/.global/shell_common

shopt -s checkwinsize      # check the window size after each command
shopt -s cdspell           # This will correct minor spelling errors in a cd command.
shopt -s histappend        # Append to history rather than overwrite
#shopt -s dotglob           # files beginning with . to be areturned in the results of path-name expansion.

# Load alias definitions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Bash Prompt
YELLOW='\[\e[1;93m\]'
BLUE='\[\e[1;34m\]'
RED='\[\e[1;31m\]'
GREEN='\[\e[1;92m\]'
NC='\[\e[0m\]'  
PS1="${GREEN}\u${RED}@${BLUE}\w${RED}\$${NC} "
