""
"" Thor's vimrc
""

" Only run the script once
if exists("g:did_myvimrc")
  finish
endif

let g:did_myvimrc = 1

" No vi compatibility!:
set nocompatible     
" Line Numbers
set number           
" Spaces instead of tab characters
set expandtab        
" Indentation width for autoindent
set shiftwidth=2     
" Width to display tab characters at
set tabstop=2        
" Spaces feel like real tabs
set softtabstop=2
" Swap case is an operator
set tildeop          
" Help vim guess my background color
set background=light
" Lots of history!
set history=10000    
" I have lots of RAM
set maxmemtot=2000000
" LOTS of RAM
set maxmem=2000000   
" Whitespace insensitive diff
set diffopt+=iwhite  
" Don't jump to start of line on page up/dwn
set nostartofline    
" Allow cursor where there's no character
set virtualedit=block
" Allow direction keys to wrap to the next line
set whichwrap=bs<>   
" Menu for auto complete
set wildmenu                  
" Completion list to longest common match and then full
set wildmode=list:longest,full "
" Use tab for wild
set wildchar=<TAB>
" Ignore some characters for completion
set wildignore=.svn,CVS,.git,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif
" Support for non-native file formats
set fileformats=unix,dos,mac 
" Do not redraw while running macros (much faster).
set lazyredraw 
" Wrap long lines at 'breakat' char instead of last character
set linebreak
" Allow current buffer to be in the background without a disk write
set hidden
" Enable non-stupid backspace key behavior
set backspace=indent,eol,start

" Enable the ruler with the format:
" {buffer number}{modified/readonly flag}: {file type}
" [current line, current column] {position percentage in file}
set ruler
set rulerformat=%25(%n%m%r:\ %Y\ [%l,%v]\ %p%%%)

" Configure Status Line
set statusline = "%f\\ %h%m%r%=%l,%v\\ \\ \\ \\ %P" 
set laststatus=2 

" Enable C indenting
set cindent
" C Indent Keystring
set cinkeys=0{,0},0),:,!^F,o,0,e " default is 0{,0},0),:,0#,!^F,o,0,e

" Start scrolling 3 lines before the cursor reaches the bottom
set scrolloff=3

" save backups centrally
set backupdir=~/.vim
set directory=~/.vim

" remember some stuff after quiting vim:
" marks, registers, searches, buffer list
set viminfo='20,<50,s10,h,%

" Disable bell
set noerrorbells

" Colorize NERDTree
let NERDChristmasTree = 1

" Ruby autocomplete
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1

if &t_Co > 2 
    syntax on
    set hlsearch
    set incsearch 
endif

" This is sort of a hack, but t_Co never seems to get set correctly
set t_Co=256
colorscheme desert256
