###
# My zshrc
###

source ~/.global/shell_common

# Load alias definitions
if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi

# Initialize colors.
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Set the prompt.

# %F{color} starts using a color
# %~ is pwd
# $f stops using a color
# %# is % for non-root shells and # for root shells

PROMPT='%F{red}%~%f
%F{blue}%#%f '
