###
# My zshrc
###

source ~/.global/shell_common

# Load alias definitions
if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi

# Initialize colors.
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Set the prompt.
PROMPT=$'%{${fg[red]}%}%B%~%b${fg[green]}
%# ${fg[default]}%'
